### FOUNDATIONAL SERVICES ###
airflow-postgres:
  image: spals/airflow-postgres:9.6.2
  ports:
    - ${AIRFLOW_POSTGRES_PORT}:5432
  environment:
    AIRFLOW_POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    AIRFLOW_POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}

airflow-server:
  image: spals/airflow:1.7.1.3
  volumes:
    - $HOME/.airflow:/usr/local/airflow/dags
  environment:
    AIRFLOW_EXECUTOR: LocalExecutor
    AIRFLOW_POSTGRES_HOST: ${AIRFLOW_POSTGRES_HOST}
    AIRFLOW_POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    AIRFLOW_POSTGRES_PORT: ${AIRFLOW_POSTGRES_PORT}
    AIRFLOW_POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
    DAGS_PAUSED_AT_CREATION: 'True'
  command: scheduler

airflow-ui:
  image: spals/airflow:1.7.1.3
  ports:
    - ${AIRFLOW_UI_PORT}:8080
  volumes:
    - $HOME/.airflow:/usr/local/airflow/dags
  environment:
    AIRFLOW_EXECUTOR: LocalExecutor
    AIRFLOW_POSTGRES_HOST: ${AIRFLOW_POSTGRES_HOST}
    AIRFLOW_POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    AIRFLOW_POSTGRES_PORT: ${AIRFLOW_POSTGRES_PORT}
    AIRFLOW_POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
    DAGS_PAUSED_AT_CREATION: 'True'
  links:
    - airflow-server
  command: webserver

