### FOUNDATIONAL SERVICES ###
airflow-postgres:
  image: spals/airflow-postgres:9.6.2
  ports:
    - ${AIRFLOW_POSTGRES_PORT}:5432
  environment:
    AIRFLOW_POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    AIRFLOW_POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
