### FOUNDATIONAL SERVICES ###
#
# These are third party services which
# are pre-requisites for running the
# BTS57 backend.
#############################
mysql:
  image: mysql:5.7
  ports:
    - ${MYSQL_PORT}:3306
  env_file:
    - ./spals-backend.env
  volumes:
    - ~/data/spals/mysql:/var/lib/mysql

